---

# network configuration
vpc_name: "rhauto-net"
vpc_auto_create_subnetworks: false

# subnet configuration
subnet_name: "rhauto-subnet"
subnet_cidr: "10.0.0.0/24"

# Firewall Rules
firewall_allow_ssh_http_https: "allow-ssh-http-https"
firewall_allow_internal: "allow-internal"
firewall_allow_egress: "allow-all-egress"

# VM Instance Configuration
vm_name: "rhauto-vm"
vm_machine_type: "c4a-highmem-96-metal"
vm_network_tier: "PREMIUM"

# Disk Configuration
boot_disk_size_gb: 20
boot_disk_type: "hyperdisk-balanced"
boot_disk_auto_delete: true

data_disk_name: "data-disk"
data_disk_size_gb: 200
data_disk_type: "hyperdisk-balanced"
data_disk_auto_delete: true

# OS Image Configuration
os_image_project: "rhel-cloud"
os_image_family: "rhel-10-arm64"

# Tags for the VM
vm_tags:
  - rhauto
  - http
  - https
  - ssh

# volume mount point
volume_mount_point: "/mnt/data"