# Implement your uninstall deployment tasks here
# -------------------------------------------------

- name: delete vm instance
  google.cloud.gcp_compute_instance:
    name: "{{ instance_name }}"
    zone: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent

- name: delete data disk (if it exists)
  google.cloud.gcp_compute_disk:
    name: "{{ data_disk_name }}"
    zone: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent

- name: delete VPC network (cascades subnet, routes, firewall rules)
  google.cloud.gcp_compute_network:
    name: "{{ vpc_name }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent

